/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerOnboardingRouteImport } from './routes/worker-onboarding'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostJobSuccessRouteImport } from './routes/post-job-success'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ClientOnboardingRouteImport } from './routes/client-onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RateJobIdRouteImport } from './routes/rate.$jobId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DisputeJobIdRouteImport } from './routes/dispute.$jobId'
import { Route as ChatJobIdOtherIdRouteImport } from './routes/chat.$jobId.$otherId'

const WorkerOnboardingRoute = WorkerOnboardingRouteImport.update({
  id: '/worker-onboarding',
  path: '/worker-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobSuccessRoute = PostJobSuccessRouteImport.update({
  id: '/post-job-success',
  path: '/post-job-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOnboardingRoute = ClientOnboardingRouteImport.update({
  id: '/client-onboarding',
  path: '/client-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RateJobIdRoute = RateJobIdRouteImport.update({
  id: '/rate/$jobId',
  path: '/rate/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeJobIdRoute = DisputeJobIdRouteImport.update({
  id: '/dispute/$jobId',
  path: '/dispute/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatJobIdOtherIdRoute = ChatJobIdOtherIdRouteImport.update({
  id: '/chat/$jobId/$otherId',
  path: '/chat/$jobId/$otherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/post-job-success': typeof PostJobSuccessRoute
  '/profile': typeof ProfileRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/worker-onboarding': typeof WorkerOnboardingRoute
  '/dispute/$jobId': typeof DisputeJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/rate/$jobId': typeof RateJobIdRoute
  '/chat/$jobId/$otherId': typeof ChatJobIdOtherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/post-job-success': typeof PostJobSuccessRoute
  '/profile': typeof ProfileRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/worker-onboarding': typeof WorkerOnboardingRoute
  '/dispute/$jobId': typeof DisputeJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/rate/$jobId': typeof RateJobIdRoute
  '/chat/$jobId/$otherId': typeof ChatJobIdOtherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/post-job-success': typeof PostJobSuccessRoute
  '/profile': typeof ProfileRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/worker-onboarding': typeof WorkerOnboardingRoute
  '/dispute/$jobId': typeof DisputeJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/rate/$jobId': typeof RateJobIdRoute
  '/chat/$jobId/$otherId': typeof ChatJobIdOtherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-onboarding'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/post-job-success'
    | '/profile'
    | '/role-select'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/worker-onboarding'
    | '/dispute/$jobId'
    | '/jobs/$jobId'
    | '/rate/$jobId'
    | '/chat/$jobId/$otherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-onboarding'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/post-job-success'
    | '/profile'
    | '/role-select'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/worker-onboarding'
    | '/dispute/$jobId'
    | '/jobs/$jobId'
    | '/rate/$jobId'
    | '/chat/$jobId/$otherId'
  id:
    | '__root__'
    | '/'
    | '/client-onboarding'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/post-job-success'
    | '/profile'
    | '/role-select'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/worker-onboarding'
    | '/dispute/$jobId'
    | '/jobs/$jobId'
    | '/rate/$jobId'
    | '/chat/$jobId/$otherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientOnboardingRoute: typeof ClientOnboardingRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PostJobRoute: typeof PostJobRoute
  PostJobSuccessRoute: typeof PostJobSuccessRoute
  ProfileRoute: typeof ProfileRoute
  RoleSelectRoute: typeof RoleSelectRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkerOnboardingRoute: typeof WorkerOnboardingRoute
  DisputeJobIdRoute: typeof DisputeJobIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  RateJobIdRoute: typeof RateJobIdRoute
  ChatJobIdOtherIdRoute: typeof ChatJobIdOtherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-onboarding': {
      id: '/worker-onboarding'
      path: '/worker-onboarding'
      fullPath: '/worker-onboarding'
      preLoaderRoute: typeof WorkerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job-success': {
      id: '/post-job-success'
      path: '/post-job-success'
      fullPath: '/post-job-success'
      preLoaderRoute: typeof PostJobSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-onboarding': {
      id: '/client-onboarding'
      path: '/client-onboarding'
      fullPath: '/client-onboarding'
      preLoaderRoute: typeof ClientOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate/$jobId': {
      id: '/rate/$jobId'
      path: '/rate/$jobId'
      fullPath: '/rate/$jobId'
      preLoaderRoute: typeof RateJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute/$jobId': {
      id: '/dispute/$jobId'
      path: '/dispute/$jobId'
      fullPath: '/dispute/$jobId'
      preLoaderRoute: typeof DisputeJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$jobId/$otherId': {
      id: '/chat/$jobId/$otherId'
      path: '/chat/$jobId/$otherId'
      fullPath: '/chat/$jobId/$otherId'
      preLoaderRoute: typeof ChatJobIdOtherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientOnboardingRoute: ClientOnboardingRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PostJobRoute: PostJobRoute,
  PostJobSuccessRoute: PostJobSuccessRoute,
  ProfileRoute: ProfileRoute,
  RoleSelectRoute: RoleSelectRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  WorkerOnboardingRoute: WorkerOnboardingRoute,
  DisputeJobIdRoute: DisputeJobIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  RateJobIdRoute: RateJobIdRoute,
  ChatJobIdOtherIdRoute: ChatJobIdOtherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
